export async function GET(req) {
	const data = [
    {
        "id": 1,
        "type": "perfume",
        "brand": "Chanel",
        "title": "Allure",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 91.58,
        "featured": true,
    },
    {
        "id": 2,
        "type": "perfume",
        "brand": "Chanel",
        "title": "Coco Refill",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "60 ml",
        "price": 83.52,
        "featured": true,
    },
    {
        "id": 3,
        "type": "perfume",
        "brand": "Dior",
        "title": "J'adore",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 76.68,
        "featured": true,
    },
    {
        "id": 4,
        "type": "perfume",
        "featured": false,
        "brand": "Dior",
        "title": "J'adore",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 105.23
    },
    {
        "id": 5,
        "type": "perfume",
        "featured": false,
        "brand": "Giorgio Armani",
        "title": "Code",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "75 ml",
        "price": 73.68
    },
    {
        "id": 6,
        "type": "perfume",
        "featured": false,
        "brand": "Giorgio Armani",
        "title": "Code",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 61.34
    },
    {
        "id": 7,
        "type": "perfume",
        "featured": false,
        "brand": "Mugler",
        "title": "Alien",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "30 ml",
        "price": 46.54
    },
    {
        "id": 8,
        "type": "perfume",
        "featured": false,
        "brand": "Mugler",
        "title": "Alien",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "60 ml",
        "price": 64.52
    },
    {
        "id": 9,
        "type": "perfume",
        "featured": false,
        "brand": "Mugler",
        "title": "Angel",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 68.59
    },
    {
        "id": 10,
        "type": "perfume",
        "featured": false,
        "brand": "Versace",
        "title": "Crystal Noir",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "90 ml",
        "price": 57.17
    },
    {
        "id": 11,
        "type": "perfume",
        "featured": false,
        "brand": "Givenchy",
        "title": "Ange ou Démon (Etrange)",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 59.85
    },
    {
        "id": 12,
        "type": "perfume",
        "featured": false,
        "brand": "Givenchy",
        "title": "Ange ou Démon (Etrange)",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 43.55
    },
    {
        "id": 13,
        "type": "perfume",
        "featured": false,
        "brand": "Givenchy",
        "title": "Ange ou Démon (Etrange)",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "30 ml",
        "price": 30.13
    },
    {
        "id": 14,
        "type": "perfume",
        "featured": false,
        "brand": "Narciso Rodriguez",
        "title": "For Her",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 54.07
    },
    {
        "id": 15,
        "type": "perfume",
        "featured": false,
        "brand": "Narciso Rodriguez",
        "title": "For Her",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 44.96
    },
    {
        "id": 16,
        "type": "perfume",
        "featured": false,
        "brand": "Mugler",
        "title": "Alien",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "90 ml",
        "price": 81.39
    },
    {
        "id": 17,
        "type": "perfume",
        "featured": false,
        "brand": "Sisley",
        "title": "Eau du Soir",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 70.99
    },
    {
        "id": 18,
        "type": "perfume",
        "featured": false,
        "brand": "Sisley",
        "title": "Eau du Soir",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 90.4
    },
    {
        "id": 19,
        "type": "perfume",
        "featured": false,
        "brand": "Sisley",
        "title": "Eau du Soir",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 103.32
    },
    {
        "id": 20,
        "type": "perfume",
        "featured": false,
        "brand": "Guerlain",
        "title": "Mitsouko",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "75 ml",
        "price": 64.97
    },
    {
        "id": 21,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Black Orchid",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 79.23
    },
    {
        "id": 22,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Black Orchid",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 98
    },
    {
        "id": 23,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Black Orchid",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "30 ml",
        "price": 68.07
    },
    {
        "id": 24,
        "type": "perfume",
        "featured": false,
        "brand": "Chanel",
        "title": "N°5",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "60 ml",
        "price": 98.7
    },
    {
        "id": 25,
        "type": "perfume",
        "featured": false,
        "brand": "Chanel",
        "title": "N°5 Twist and Spray 3x 20 ml",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "20 ml",
        "price": 106.84
    },
    {
        "id": 26,
        "type": "perfume",
        "featured": false,
        "brand": "Dior",
        "title": "Dior Homme Intense 2020",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "150 ml",
        "price": 104.82
    },
    {
        "id": 27,
        "type": "perfume",
        "featured": false,
        "brand": "Dior",
        "title": "Dior Homme Intense 2020",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 85.28
    },
    {
        "id": 28,
        "type": "perfume",
        "featured": false,
        "brand": "Dior",
        "title": "Dior Homme Intense 2020",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "50 ml",
        "price": 61.87
    },
    {
        "id": 29,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Aoud Queen Roses",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 47.99
    },
    {
        "id": 30,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "White Musk",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 48.81
    },
    {
        "id": 31,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Amber & Spices",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 48.65
    },
    {
        "id": 32,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Aoud Lime",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 50.42
    },
    {
        "id": 33,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Aoud Purple Rose",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 48.21
    },
    {
        "id": 34,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Black Musk",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 46.85
    },
    {
        "id": 35,
        "type": "perfume",
        "featured": false,
        "brand": "Bentley",
        "title": "Bentley For Men Intense",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 21.95
    },
    {
        "id": 36,
        "type": "perfume",
        "featured": false,
        "brand": "Serge Lutens",
        "title": "La Fille de Berlin",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 51.01
    },
    {
        "id": 37,
        "type": "perfume",
        "featured": false,
        "brand": "Juliette Has A Gun",
        "title": "Not A Perfume",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 34.96
    },
    {
        "id": 38,
        "type": "perfume",
        "featured": false,
        "brand": "Givenchy",
        "title": "Ange ou Démon (Etrange) Le Secret 2014",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 67.87
    },
    {
        "id": 39,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Velvet Orchid",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 100.6
    },
    {
        "id": 40,
        "type": "perfume",
        "featured": false,
        "brand": "Chanel",
        "title": "Allure Homme Edition Blanche",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 105.93
    },
    {
        "id": 41,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Blanche",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 153.82
    },
    {
        "id": 42,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Black Saffron",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 147.54
    },
    {
        "id": 43,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Palermo",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 145.73
    },
    {
        "id": 44,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Inflorescence",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 147.39
    },
    {
        "id": 45,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Aoud Black Candy",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "120 ml",
        "price": 54.92
    },
    {
        "id": 46,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Intense Cafe",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 54.77
    },
    {
        "id": 47,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Boisé Vanillé",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 51.3
    },
    {
        "id": 48,
        "type": "perfume",
        "featured": false,
        "brand": "Histoires de Parfums",
        "title": "1804",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "120 ml",
        "price": 62.51
    },
    {
        "id": 49,
        "type": "perfume",
        "featured": false,
        "brand": "Histoires de Parfums",
        "title": "Characters 1826",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "60 ml",
        "price": 40.43
    },
    {
        "id": 50,
        "type": "perfume",
        "featured": false,
        "brand": "Histoires de Parfums",
        "title": "1876",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "60 ml",
        "price": 40.15
    },
    {
        "id": 51,
        "type": "perfume",
        "featured": false,
        "brand": "By Kilian",
        "title": "The Cellars Sacred Wood",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 152.47
    },
    {
        "id": 52,
        "type": "perfume",
        "featured": false,
        "brand": "By Kilian",
        "title": "The Cellars Straight to Heaven White Cristal",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "4x7,5 ml",
        "price": 109.95
    },
    {
        "id": 53,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Neroli Portofino",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 174.91
    },
    {
        "id": 54,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Private Blend Oud Wood",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 189.75
    },
    {
        "id": 55,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Noir de Noir",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 143.65
    },
    {
        "id": 56,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Tuscan Leather",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 149.29
    },
    {
        "id": 57,
        "type": "perfume",
        "featured": false,
        "brand": "Guerlain",
        "title": "La Petite Robe Noire Intense",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 76.11
    },
    {
        "id": 58,
        "type": "perfume",
        "featured": false,
        "brand": "Guerlain",
        "title": "Mon Guerlain",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 73.69
    },
    {
        "id": 59,
        "type": "perfume",
        "featured": false,
        "brand": "Guerlain",
        "title": "Mon Guerlain",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 52.96
    },
    {
        "id": 60,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Oud Immortel",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 98.26
    },
    {
        "id": 61,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Rose Of No Man's Land",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 102.93
    },
    {
        "id": 62,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Bibliothèque",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 149.85
    },
    {
        "id": 63,
        "type": "perfume",
        "featured": false,
        "brand": "Acqua di Parma",
        "title": "Signatures Of The Sun Oud",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 104.65
    },
    {
        "id": 64,
        "type": "perfume",
        "featured": false,
        "brand": "Acqua di Parma",
        "title": "Signatures Of The Sun Oud",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "180 ml",
        "price": 139.26
    },
    {
        "id": 65,
        "type": "perfume",
        "featured": false,
        "brand": "Amouage",
        "title": "Love Mimosa",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 120.33
    },
    {
        "id": 66,
        "type": "perfume",
        "featured": false,
        "brand": "By Kilian",
        "title": "The Narcotics Liaisons Dangereuses  Typical Me",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 152.47
    },
    {
        "id": 67,
        "type": "perfume",
        "featured": false,
        "brand": "By Kilian",
        "title": "The Cellars Intoxicated",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 152.47
    },
    {
        "id": 68,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Fucking Fabulous",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 266.85
    },
    {
        "id": 69,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "White Suede",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 158.59
    },
    {
        "id": 70,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Francis Kurkdjian",
        "title": "A La Rose",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "5x11 ml",
        "price": 150.77
    },
    {
        "id": 71,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Francis Kurkdjian",
        "title": "Oud Satin Mood",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "3x11 ml",
        "price": 93.75
    },
    {
        "id": 72,
        "type": "perfume",
        "featured": false,
        "brand": "Creed",
        "title": "Silver Mountain Water",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 188.28
    },
    {
        "id": 73,
        "type": "perfume",
        "featured": false,
        "brand": "Guerlain",
        "title": "Mon Guerlain Intense",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 52.4
    },
    {
        "id": 74,
        "type": "perfume",
        "featured": false,
        "brand": "Yves Saint Laurent",
        "title": "L'Homme Le Parfum",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 68.46
    },
    {
        "id": 75,
        "type": "perfume",
        "featured": false,
        "brand": "Histoires de Parfums",
        "title": "7753 Unexpected Mona",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "60 ml",
        "price": 40.43
    },
    {
        "id": 76,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Intense Black Aoud",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 63.03
    },
    {
        "id": 77,
        "type": "perfume",
        "featured": false,
        "brand": "MANCERA",
        "title": "Aoud Orchid",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "120 ml",
        "price": 54.62
    },
    {
        "id": 78,
        "type": "perfume",
        "featured": false,
        "brand": "MANCERA",
        "title": "Les Confidentiels Black Vanilla",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "120 ml",
        "price": 63.34
    },
    {
        "id": 79,
        "type": "perfume",
        "featured": false,
        "brand": "MANCERA",
        "title": "Musk Of Flowers",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "120 ml",
        "price": 41.25
    },
    {
        "id": 80,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Francis Kurkdjian",
        "title": "L'Homme A La Rose",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "70 ml",
        "price": 132.27
    },
    {
        "id": 81,
        "type": "perfume",
        "featured": false,
        "brand": "Serge Lutens",
        "title": "Nuit de Cellophane",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 73.74
    },
    {
        "id": 82,
        "type": "perfume",
        "featured": false,
        "brand": "MANCERA",
        "title": "Intense Black Collection Black Intensitive Aoud",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "120 ml",
        "price": 49.33
    },
    {
        "id": 83,
        "type": "perfume",
        "featured": false,
        "brand": "MANCERA",
        "title": "Les Confidentiels Pink Roses",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "120 ml",
        "price": 54.07
    },
    {
        "id": 84,
        "type": "perfume",
        "featured": false,
        "brand": "MANCERA",
        "title": "Les Exclusifs Vanille Exclusive",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "120 ml",
        "price": 56.92
    },
    {
        "id": 85,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Oud Tobacco",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 56.26
    },
    {
        "id": 86,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Private Blend Bitter Peach",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 182.12
    },
    {
        "id": 87,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Soleil Brulant",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 176.16
    },
    {
        "id": 88,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "1996 Inez & Vinoodh",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 102.47
    },
    {
        "id": 89,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Lil Fleur",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 129.52
    },
    {
        "id": 90,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Malaki Rose",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "80 ml",
        "price": 34.57
    },
    {
        "id": 91,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Malaki Amber",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "80 ml",
        "price": 32.83
    },
    {
        "id": 92,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Malaki Black Incense",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "80 ml",
        "price": 45.67
    },
    {
        "id": 93,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Malaki Oud",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "80 ml",
        "price": 45.88
    },
    {
        "id": 94,
        "type": "perfume",
        "featured": false,
        "brand": "Jean Patou",
        "title": "Collection Héritage L'Heure Attendue",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 44.15
    },
    {
        "id": 95,
        "type": "perfume",
        "featured": false,
        "brand": "Jean Patou",
        "title": "Collection Héritage Vacances",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 49.81
    },
    {
        "id": 96,
        "type": "perfume",
        "featured": false,
        "brand": "Jean Patou",
        "title": "Collection Héritage Chaldée",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 49.81
    },
    {
        "id": 97,
        "type": "perfume",
        "featured": false,
        "brand": "Jean Patou",
        "title": "Collection Héritage Deux Amours",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 49.81
    },
    {
        "id": 98,
        "type": "perfume",
        "featured": false,
        "brand": "Jean Patou",
        "title": "Collection Héritage Adieu Sagesse",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 49.81
    },
    {
        "id": 99,
        "type": "perfume",
        "featured": false,
        "brand": "Jean Patou",
        "title": "Collection Héritage Que Sais-Je?",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 49.81
    },
    {
        "id": 100,
        "type": "perfume",
        "featured": false,
        "brand": "Bentley",
        "title": "Beyond Collection Radiant Osmanthus",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 90.9
    },
    {
        "id": 101,
        "type": "perfume",
        "featured": false,
        "brand": "Bentley",
        "title": "Beyond Collection Vibrant Hibiscus",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 90.9
    },
    {
        "id": 102,
        "type": "perfume",
        "featured": false,
        "brand": "Bentley",
        "title": "Beyond Collection Mellow Heliotrope",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 90.9
    },
    {
        "id": 103,
        "type": "perfume",
        "featured": false,
        "brand": "Bentley",
        "title": "Beyond Collection Wild Vetiver",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 90.9
    },
    {
        "id": 104,
        "type": "perfume",
        "featured": false,
        "brand": "Montale",
        "title": "Intense Black Aoud",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "2 ml",
        "price": 1.36
    },
    {
        "id": 105,
        "type": "perfume",
        "featured": false,
        "brand": "Lalique",
        "title": "Les Compositions Parfumées Infinite Shine",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 58.15
    },
    {
        "id": 106,
        "type": "perfume",
        "featured": false,
        "brand": "Lalique",
        "title": "Les Compositions Parfumées Spicy Electrum",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 58.15
    },
    {
        "id": 107,
        "type": "perfume",
        "featured": false,
        "brand": "Histoires de Parfums",
        "title": "This Is Not A Blue Bottle 1.5",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "60 ml",
        "price": 40.43
    },
    {
        "id": 108,
        "type": "perfume",
        "featured": false,
        "brand": "Histoires de Parfums",
        "title": "1876",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "120 ml",
        "price": 61.79
    },
    {
        "id": 109,
        "type": "perfume",
        "featured": false,
        "brand": "Histoires de Parfums",
        "title": "1472 La Divina Commedia",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "120 ml",
        "price": 62.22
    },
    {
        "id": 110,
        "type": "perfume",
        "featured": false,
        "brand": "Hermes",
        "title": "L’Ombre des Merveilles",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "30 ml",
        "price": 36.29
    },
    {
        "id": 111,
        "type": "perfume",
        "featured": false,
        "brand": "TOM FORD",
        "title": "Private Blend Tubéreuse Nue",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 147.31
    },
    {
        "id": 112,
        "type": "perfume",
        "featured": false,
        "brand": "Dior",
        "title": "J'adore Parfum d’Eau",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 105.23
    },
    {
        "id": 113,
        "type": "perfume",
        "featured": false,
        "brand": "Etat Libre d'Orange",
        "title": "Fat Electrician",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 49.43
    },
    {
        "id": 114,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Mumbai Noise",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 138.46,
        "category": "Niche"
    },
    {
        "id": 115,
        "type": "perfume",
        "featured": false,
        "brand": "BYREDO",
        "title": "Mumbai Noise",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 103.14,
        "category": "Niche"
    },
    {
        "id": 116,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Francis Kurkdjian",
        "title": "Aqua Universalis Forte",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "35 ml",
        "price": 101.79,
        "category": "Niche"
    },
    {
        "id": 117,
        "type": "perfume",
        "featured": false,
        "brand": "Carner Barcelona",
        "title": "Sandor 70's",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 52.02,
        "category": "Niche"
    },
    {
        "id": 118,
        "type": "perfume",
        "featured": false,
        "brand": "MANCERA",
        "title": "Of The Wild",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "120 ml",
        "price": 53.6,
        "category": "Niche"
    },
    {
        "id": 119,
        "type": "perfume",
        "featured": false,
        "brand": "Acqua di Parma",
        "title": "Signatures Of The Sun Zafferano",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "180 ml",
        "price": 140.07,
        "category": "Premium"
    },
    {
        "id": 120,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Love Chopard",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 31.79,
        "category": "Premium"
    },
    {
        "id": 121,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Love Chopard",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 42.35,
        "category": "Premium"
    },
    {
        "id": 122,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Malaki Musk",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "80 ml",
        "price": 45.88,
        "category": "Premium"
    },
    {
        "id": 123,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Imperiale Iris Malika",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 45.88,
        "category": "Premium"
    },
    {
        "id": 124,
        "type": "perfume",
        "featured": false,
        "brand": "Elie Saab",
        "title": "Le Parfum Lumière",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 39.39,
        "category": "Premium"
    },
    {
        "id": 125,
        "type": "perfume",
        "featured": false,
        "brand": "Elie Saab",
        "title": "Girl of Now Lovely",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 36.83,
        "category": "Premium"
    },
    {
        "id": 126,
        "type": "perfume",
        "featured": false,
        "brand": "Dolce&Gabbana",
        "title": "Q",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 58.37,
        "category": "Premium"
    },
    {
        "id": 127,
        "type": "perfume",
        "featured": false,
        "brand": "Dolce&Gabbana",
        "title": "Q",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 39.46,
        "category": "Premium"
    },
    {
        "id": 128,
        "type": "perfume",
        "featured": false,
        "brand": "Dolce&Gabbana",
        "title": "Q",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "30 ml",
        "price": 32.6,
        "category": "Premium"
    },
    {
        "id": 129,
        "type": "perfume",
        "featured": false,
        "brand": "Orientica",
        "title": "de Orientica Rosé de Orientica",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "90 ml",
        "price": 37.3,
        "category": "Heritage"
    },
    {
        "id": 130,
        "type": "perfume",
        "featured": false,
        "brand": "Orientica",
        "title": "de Orientica Cuir de Orientica",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "90 ml",
        "price": 26.98,
        "category": "Heritage"
    },
    {
        "id": 131,
        "type": "perfume",
        "featured": false,
        "brand": "Orientica",
        "title": "Luxury Collection Oud Saffron",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "80 ml",
        "price": 45.03,
        "category": "Heritage"
    },
    {
        "id": 132,
        "type": "perfume",
        "featured": false,
        "brand": "Orientica",
        "title": "Luxury Collection Amber Rouge",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "80 ml",
        "price": 45.13,
        "category": "Heritage"
    },
    {
        "id": 133,
        "type": "perfume",
        "featured": false,
        "brand": "Orientica",
        "title": "Luxury Collection Royal Bleu",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "80 ml",
        "price": 45.13,
        "category": "Heritage"
    },
    {
        "id": 134,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "L'Aventure Femme",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 24.83,
        "category": "Heritage"
    },
    {
        "id": 135,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "Amber Oud Tobacco Edition",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "60 ml",
        "price": 36.74,
        "category": "Heritage"
    },
    {
        "id": 136,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "Amber Oud",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "60 ml",
        "price": 33.5,
        "category": "Heritage"
    },
    {
        "id": 137,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "Amber Oud Ultra Violet",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "60 ml",
        "price": 47.79,
        "category": "Heritage"
    },
    {
        "id": 138,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "Amber Musk",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 33.5,
        "category": "Heritage"
    },
    {
        "id": 139,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "Opulent Sapphire",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 40.24,
        "category": "Heritage"
    },
    {
        "id": 140,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "Portfolio Royale Stallion",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "75 ml",
        "price": 58.06,
        "category": "Heritage"
    },
    {
        "id": 141,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "Portfolio Euphoric Roots",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "75 ml",
        "price": 44.66,
        "category": "Heritage"
    },
    {
        "id": 142,
        "type": "perfume",
        "featured": false,
        "brand": "Al Haramain",
        "title": "Portfolio Black Oud",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "75 ml",
        "price": 58.06,
        "category": "Heritage"
    },
    {
        "id": 143,
        "type": "perfume",
        "featured": false,
        "brand": "Molinard",
        "title": "Habanita",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 50.97,
        "category": "Heritage"
    },
    {
        "id": 144,
        "type": "perfume",
        "featured": false,
        "brand": "David Beckham",
        "title": "True Instinct",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "50 ml",
        "price": 8.49
    },
    {
        "id": 145,
        "type": "perfume",
        "featured": false,
        "brand": "David Beckham",
        "title": "Bold Instinct",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "50 ml",
        "price": 15.86
    },
    {
        "id": 146,
        "type": "perfume",
        "featured": false,
        "brand": "David Beckham",
        "title": "Bold Instinct",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "75 ml",
        "price": 17.01
    },
    {
        "id": 147,
        "type": "perfume",
        "featured": false,
        "brand": "David Beckham",
        "title": "Follow Your Instinct",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "50 ml",
        "price": 16.11
    },
    {
        "id": 148,
        "type": "perfume",
        "featured": false,
        "brand": "Montblanc",
        "title": "Explorer Platinum",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "60 ml",
        "price": 28.5
    },
    {
        "id": 149,
        "type": "perfume",
        "featured": false,
        "brand": "HUGO BOSS",
        "title": "Boss The Scent",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 36.58
    },
    {
        "id": 150,
        "type": "perfume",
        "featured": false,
        "brand": "Calvin Klein",
        "title": "Eternity",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 37.07
    },
    {
        "id": 151,
        "type": "perfume",
        "featured": false,
        "brand": "Marc Jacobs",
        "title": "Perfect",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 60.3
    },
    {
        "id": 152,
        "type": "perfume",
        "featured": false,
        "brand": "Franck Olivier",
        "title": "One Kiss",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "75 ml",
        "price": 10.9
    },
    {
        "id": 153,
        "type": "perfume",
        "featured": false,
        "brand": "Franck Olivier",
        "title": "Giorgia L'Imperatrice",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "75 ml",
        "price": 10.9
    },
    {
        "id": 154,
        "type": "perfume",
        "featured": false,
        "brand": "Franck Olivier",
        "title": "Bella In Paris",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "75 ml",
        "price": 12.15
    },
    {
        "id": 155,
        "type": "perfume",
        "featured": false,
        "brand": "Armaf",
        "title": "Club de Nuit Blue Iconic",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "105 ml",
        "price": 28.4
    },
    {
        "id": 156,
        "type": "perfume",
        "featured": false,
        "brand": "DKNY",
        "title": "DKNY Women Energizing 2011",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 37.31
    },
    {
        "id": 157,
        "type": "perfume",
        "featured": false,
        "brand": "Trussardi",
        "title": "Trussardi Ruby Red",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "90 ml",
        "price": 25.63
    },
    {
        "id": 158,
        "type": "perfume",
        "featured": false,
        "brand": "Armaf",
        "title": "Club de Nuit White Imperiale",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "105 ml",
        "price": 27.4
    },
    {
        "id": 159,
        "type": "perfume",
        "featured": false,
        "brand": "Armaf",
        "title": "Club de Nuit Untold",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "105 ml",
        "price": 29.04
    },
    {
        "id": 160,
        "type": "perfume",
        "featured": false,
        "brand": "Boucheron",
        "title": "Singulier",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "50 ml",
        "price": 20.4
    },
    {
        "id": 161,
        "type": "perfume",
        "featured": false,
        "brand": "Trussardi",
        "title": "Trussardi Ruby Red",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "30 ml",
        "price": 19.53
    },
    {
        "id": 162,
        "type": "perfume",
        "featured": false,
        "brand": "Trussardi",
        "title": "Trussardi Ruby Red",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "60 ml",
        "price": 26.98
    },
    {
        "id": 163,
        "type": "perfume",
        "featured": false,
        "brand": "Shiseido",
        "title": "Zen Gold Elixir",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 48.59
    },
    {
        "id": 164,
        "type": "perfume",
        "featured": false,
        "brand": "Women'Secret",
        "title": "Rose Seduction",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 6.86
    },
    {
        "id": 165,
        "type": "perfume",
        "featured": false,
        "brand": "Cacharel",
        "title": "Yes I Am",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 38.52
    },
    {
        "id": 166,
        "type": "perfume",
        "featured": false,
        "brand": "Viktor & Rolf",
        "title": "Flowerbomb Ruby Orchid",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 96.39
    },
    {
        "id": 167,
        "type": "perfume",
        "featured": false,
        "brand": "Azzaro",
        "title": "Wanted",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 54.46
    },
    {
        "id": 168,
        "type": "perfume",
        "featured": false,
        "brand": "HUGO BOSS",
        "title": "Boss Bottled",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "50 ml",
        "price": 29.15
    },
    {
        "id": 169,
        "type": "perfume",
        "featured": false,
        "brand": "Lattafa",
        "title": "Ana Abiyedh Rouge",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "60 ml",
        "price": 13.2
    },
    {
        "id": 170,
        "type": "perfume",
        "featured": false,
        "brand": "Lattafa",
        "title": "Confidential Private Gold",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 12.26
    },
    {
        "id": 171,
        "type": "perfume",
        "featured": false,
        "brand": "Lattafa",
        "title": "Qimmah",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 11.14
    },
    {
        "id": 172,
        "type": "perfume",
        "featured": false,
        "brand": "Lattafa",
        "title": "Raghba Wood Intense",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 10.57
    },
    {
        "id": 173,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Alhambra",
        "title": "Infini Oud",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 15.29
    },
    {
        "id": 174,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Alhambra",
        "title": "Galatea",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 12.29
    },
    {
        "id": 175,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Alhambra",
        "title": "La Vita",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 10.59
    },
    {
        "id": 176,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Alhambra",
        "title": "Berlinetta",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 15.68
    },
    {
        "id": 177,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Alhambra",
        "title": "Kismet",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 22.95
    },
    {
        "id": 178,
        "type": "perfume",
        "featured": false,
        "brand": "Tom Ford",
        "title": "Black Orchid",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "150 ml",
        "price": 125.8
    },
    {
        "id": 179,
        "type": "perfume",
        "featured": false,
        "brand": "Tom Ford",
        "title": "Private Blend Bois Marocain",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "50 ml",
        "price": 133.5
    },
    {
        "id": 180,
        "type": "perfume",
        "featured": false,
        "brand": "Guerlain",
        "title": "Samsara",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "75 ml",
        "price": 63.32
    },
    {
        "id": 181,
        "type": "perfume",
        "featured": false,
        "brand": "Guerlain",
        "title": "Nahema",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "75 ml",
        "price": 58.96
    },
    {
        "id": 182,
        "type": "perfume",
        "featured": false,
        "brand": "Hermes",
        "title": "Terre d’Hermès Eau Givrée",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 58.63
    },
    {
        "id": 183,
        "type": "perfume",
        "featured": false,
        "brand": "Sisley",
        "title": "Eau du Soir",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 99.14
    },
    {
        "id": 184,
        "type": "perfume",
        "featured": false,
        "brand": "Viktor & Rolf",
        "title": "Flowerbomb Ruby Orchid",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 96.39
    },
    {
        "id": 185,
        "type": "perfume",
        "featured": false,
        "brand": "Mugler",
        "title": "Angel Elixir",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 91.29
    },
    {
        "id": 186,
        "type": "perfume",
        "featured": false,
        "brand": "Carolina Herrera",
        "title": "Very Good Girl",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 59.4
    },
    {
        "id": 187,
        "type": "perfume",
        "featured": false,
        "brand": "Serge Lutens",
        "title": "La Fille de Berlin",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 62.69
    },
    {
        "id": 188,
        "type": "perfume",
        "featured": false,
        "brand": "Acqua di Parma",
        "title": "Signatures Of The Sun Magnolia Infinita",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 102.97
    },
    {
        "id": 189,
        "type": "perfume",
        "featured": false,
        "brand": "Mugler",
        "title": "Alien",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "60 ml",
        "price": 61.76
    },
    {
        "id": 190,
        "type": "perfume",
        "featured": false,
        "brand": "Giorgio Armani",
        "title": "Sì Passione",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 80.27
    },
    {
        "id": 191,
        "type": "perfume",
        "featured": false,
        "brand": "Bvlgari",
        "title": "MAN Rain Essence",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "60 ml",
        "price": 57.56
    },
    {
        "id": 192,
        "type": "perfume",
        "featured": false,
        "brand": "Frederic Malle",
        "title": "Portrait of a Lady",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "100 ml",
        "price": 298
    },
    {
        "id": 193,
        "type": "perfume",
        "featured": false,
        "brand": "Amouage",
        "title": "Interlude Man",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 260
    },
    {
        "id": 194,
        "type": "perfume",
        "featured": false,
        "brand": "Creed",
        "title": "Aventus",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "100 ml",
        "price": 325
    },
    {
        "id": 195,
        "type": "perfume",
        "featured": false,
        "brand": "Diptyque",
        "title": "Philosykos",
        "subtype": "Eau de Toilette",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 140
    },
    {
        "id": 196,
        "type": "perfume",
        "featured": false,
        "brand": "Maison Francis Kurkdjian",
        "title": "Baccarat Rouge 540",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "70 ml",
        "price": 300
    },
    {
        "id": 197,
        "type": "perfume",
        "featured": false,
        "brand": "Byredo",
        "title": "Gypsy Water",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 180
    },
    {
        "id": 198,
        "type": "perfume",
        "featured": false,
        "brand": "Niche Emarati",
        "title": "Hayaam",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 40.62
    },
    {
        "id": 199,
        "type": "perfume",
        "featured": false,
        "brand": "Niche Emarati",
        "title": "Lujain",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 40.06
    },
    {
        "id": 200,
        "type": "perfume",
        "featured": false,
        "brand": "Niche Emarati",
        "title": "Ghinwa",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 40.62
    },
    {
        "id": 201,
        "type": "perfume",
        "featured": false,
        "brand": "Niche Emarati",
        "title": "Al Jawhara",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 40.06
    },
    {
        "id": 202,
        "type": "perfume",
        "featured": false,
        "brand": "Chopard",
        "title": "Collection Rose Seljuke",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 45.89
    },
    {
        "id": 203,
        "type": "perfume",
        "featured": false,
        "brand": "Attar Collection",
        "title": "Fleur de Santal",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "100 ml",
        "price": 88.42
    },
    {
        "id": 204,
        "type": "perfume",
        "featured": false,
        "brand": "Guerlain",
        "title": "La Petite Robe Noire",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "50 ml",
        "price": 52.7
    },
    {
        "id": 205,
        "type": "perfume",
        "featured": false,
        "brand": "Creed",
        "title": "Bois du Portugal",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "50 ml",
        "price": 134.28
    },
    {
        "id": 206,
        "type": "perfume",
        "featured": false,
        "brand": "Creed",
        "title": "Carmina",
        "subtype": "Eau de Parfum",
        "sex": "W",
        "volume": "75 ml",
        "price": 193.35
    },
    {
        "id": 207,
        "type": "perfume",
        "featured": false,
        "brand": "Creed",
        "title": "Himalaya",
        "subtype": "Eau de Parfum",
        "sex": "M",
        "volume": "50 ml",
        "price": 132.6
    },
    {
        "id": 208,
        "type": "perfume",
        "featured": false,
        "brand": "Memo Paris",
        "title": "Corfu",
        "subtype": "Eau de Parfum",
        "sex": "UNI",
        "volume": "75 ml",
        "price": 106.63
    }
    ];

    // GET featured perfumes
    const url = new URL(req.url);
    const featured = url.searchParams.get('featured');
    const isFeatured = featured === 'true';
    let filteredData = data;
    if (featured !== null) {
        filteredData = data.filter(item => item.featured === isFeatured);
    }

    return new Response(JSON.stringify({ data: filteredData }), { status: 200 });    
}